server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #    url: jdbc:postgresql://10.0.4.6:5432/sirius
    url: jdbc:postgresql://127.0.0.1:5432/sirius
    username: gmc
    password: Gmc@1234!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  output:
    ansi:
      enabled: detect

logging:
  config: classpath:logback-spring.xml
  file:
    path: logs
  level:
    org.springframework: INFO
    com:
      zaxxer:
        hikari: trace
        hikari.HikariConfig: debug