name: Java CI with Maven
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Make Directory
        run: mkdir -p deploy
      - name: Copy WAR
        run: cp target/*.war ./deploy
      - name: deploy
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: websocket
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: https://kr.object.fin-ncloudstorage.com
          DEST_DIR: deploy
          SOURCE_DIR: ./deploy
      - name: SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-ssh: ${{ secrets.SSH_KEY_FLIP }}
      - name: Command
        run: whoami
